services:
  - type: web
    name: finserv-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: API_KEY
        value: hackrx-api-key-2025
